### ISSUE TITLE
trans_abund$new Error in if (ntaxa_use > sum(mean_abund > show))

### ISSUE THREAD

**Issue by nweerasu** [cran/microeco#1]
Hello!

I'm running into this error: 
Error in if (ntaxa_use > sum(mean_abund > show)) { : 
  missing value where TRUE/FALSE needed

I don't know if it's related to my actual data, but it seems like the if statement is missing the else, which is what R is looking for when I calculate the trans_abund. 

Let me know if you need some kind of reprex.
Nimalka 

Line reference:
https://github.com/cran/microeco/blob/63d9b5b3ab09850fd24fc021565c278154da8e24/R/trans_abund.R#L97

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
